name: ilocglob
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - libstdcxx-ng
  - libgcc-ng
  - icu
  - r-base
  - rpy2
  - pip:
    - torchvision
    - torchaudio
    - torch == 2.2.0
    - gpytorch
    - numpy < 2
    - scipy
    - pandas 
    - matplotlib
    - ipykernel
    - accelerate
    - datasets
    - lightning
    - ujson
    - -e ./packages/gluon-ts
    - -e ./packages/transformers
    - -e ./packages/tweediegp
