name: ilocglob
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # - libstdcxx-ng
  # - libgcc-ng
  - icu
  - r-base
  - r-nloptr
  - r-forecast
  - r-smooth
  - rpy2
  - pip:
    - torchvision
    - torchaudio
    - torch == 2.2.0
    - gpytorch
    - numpy < 2
    - scipy
    - pandas 
    - matplotlib
    - seaborn>=0.13.0,<0.14.0
    - optuna>=3.5.0,<4.4
    - optuna-integration
    - ipykernel
    - accelerate
    - datasets
    - lightning
    - ujson
    - -e ./packages/gluon-ts
    - -e ./packages/transformers
    - -e ./packages/tweediegp
    - -e ./packages/lightgbmlss
